Bump build stage memory limit to 10gb
because the process gets killed with the default 4gb, as well as with
6gb and 8gb.
The following is found in logs:

```
@stackrox/ui-components: $ tsc --build
@stackrox/platform-app: Creating an optimized production build...
@stackrox/platform-app: The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
@stackrox/platform-app: error Command failed with exit code 1.
@stackrox/platform-app: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@stackrox/platform-app'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [Makefile:33: build] Error 1
make: Leaving directory '/go/src/github.com/stackrox/rox/app/ui'
subprocess exited with status 2
subprocess exited with status 2
Error: building at STEP "RUN . /cachi2/cachi2.env &&     make -C ui build": exit status 2
```