ROX-9565: support building, pushing and testing operator on prow (#2471)
* Prefactoring: mention FROM override.

* Prefactoring: work around a kuttl issue with kubeconfig when running in a pod.

Normally, when running commands and scripts as part of a step, `kuttl` writes a
`kubeconfig` file and sets $KUBECONFIG in the environment to point to it.

However it seems that when it is running in a k8s pod it gets confused and
points $KUBECONFIG at an inexistent file.

So we smuggle the actual $KUBECONFIG behind kuttl's back in a separate
environment variable to any command that needs it.

* Prefactoring: extract "smuggled status.sh" creation from docker-build target.

* Prefactoring: work around scorecard picking up the namespace from somewhere.

When running in a pod, `operator-sdk scorcard` fails with:

```
Error: error running tests error creating ConfigMap namespaces "ci-op-05qx07r3" not found
```

This is despite unsetting the $NAMESPACE variable elsewhere.

* Prefactoring: add an option to skip index image build after preparing its source.

* Prefactoring: use a version of `opm` that can read bundle from a directory.

* Add dockerfile and script for building operator artifacts.

* Push operator images right before the next ones.

Unfortunately we need a separate function because the tag names are different
(.0 rather than .x) and not consistent (some have a "v" prefix).

Also they need to go first because the synchronization in other test jobs only
looks at the non-operator images.  This could in principle be changed, but the
pushes are surprisingly fast so we do not waste much time.

* Add endpoint and code to run openshift-*-operator-e2e-tests jobs.

* Extract operator_e2e_test_setup and unset_namespace_env_var.

* Poll for operator images from prow, rather than build them here.

* Add some kubectl statements to make debugging easier.