Specify yarn version in `packageManager` attribute
for Cachi2 to be happy.
Without the attribute, Cachi2 refuses to work with the following
error:

```
Error: PackageRejected: Unable to determine the yarn version to use to process the request
  Ensure that either yarnPath is defined in .yarnrc.yml or that packageManager is defined in package.json
```

I used the latest tag I found in
https://github.com/yarnpkg/yarn/releases

The attribute is described here
https://nodejs.org/api/packages.html#packagemanager