Restore `jq` and separate Go build and swagger steps
There's a build error without `jq`

```
xargs: jq: No such file or directory
subprocess exited with status 127
subprocess exited with status 127
Error: building at STEP "RUN . /cachi2/cachi2.env &&     make main-build-nodeps cli-build &&     mkdir -p image/rhel/docs/api/v1 &&     ./scripts/mergeswag.sh 1 generated/api/v1 central/docs/api_custom_routes >image/rhel/docs/api/v1/swagger.json &&     mkdir -p image/rhel/docs/api/v2 &&     ./scripts/mergeswag.sh 2 generated/api/v2 >image/rhel/docs/api/v2/swagger.json": exit status 127
```

https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-on-push-8rzb6

Supposedly, that's from Swagger generation scripts therefore I
separate them to have failures more isolated in the future.